name: hddi26-madelon
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - requests
  - tqdm
  - pip
  - pip:
      - umap-learn

